name: Update File

on:
  push:
    branches:
      - uat

jobs:
  update-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
    - name: Clone repo
      run: |
        git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/0akash0/update-count
        git checkout uat
        cd update-count
        ls
        git branch  
      
    - name: Increment commit count
      run: |
          count=$(($(grep -oP '(?<=My commit count is: )\d+' file.txt)+50))
          sed -i "s/My commit count is: \d\+/My commit count is: $count/" file.txt


          
        # Commit and push the changes to the other repository
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add file.txt
        git commit -m "Increment commit count"
        git remote add other_repo https://github.com/username/other-repo.git
        git push other_repo HEAD:uat
