name: Update File

on:
  push:
    branches:
      - uat

jobs:
  update-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      
    - name: Clone repository
      run: |
        git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/0akash0/update-count
        cd update-count
        git checkout uat
        ls
        git branch
      
    - name: Increment commit count
      run: |
        cd update-count      
        ls  
        COUNT=$(awk -F": " '/My commit count is/{gsub("\\.","",$2); print $2}' file.txt)
        echo "Current count: $COUNT"
        UPDATED_COUNT=$((COUNT + 50))
        echo "Updated count: $UPDATED_COUNT"
        sed -i "s/My commit count is: $COUNT/My commit count is: $UPDATED_COUNT/" file.txt

        cat ./file.txt
          
    - name: Commit and push changes to other repository
      run: |
        cd update-count      
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add file.txt
        git commit -m "Increment commit count"
        git push
